# my_site/Dockerfile.backend

FROM python:3.12-slim

WORKDIR /app

# Копируем и устанавливаем зависимости
COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бэкенда
COPY server/ .

# Порт, который будет слушать uvicorn
EXPOSE 8001

# Запуск сервера
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]